### PR TITLE
Add the boundaries to use the generic param in APDUTransport object

### LINKED ISSUE #15: Build error on git master
This is due to https://github.com/Zondax/ledger-rs/commit/8d94ced5cdd9dc3255bf0e6e775e4ec397b61f0d which made `APDUTransport` generic for native (but not wasm).

### PR DESCRIPTION
**Pull request by neithanmo**
Fixes #15

### CODE REVIEW

**Comment by DemiMarie** [comment]
This will break the build on wasm, though.

**Comment by neithanmo** [comment]
Yeah.. gonna move this to WIP..The wasm version does not have this generic, Wondering if we even need that.

**Comment by DemiMarie** [comment]
I think either both or neither need to be generic.

**Comment by jleni** [comment]
@Demi-Marie do you need WASM support in this library?

**Comment by DemiMarie** [comment]
@jleni No.

**Pull request closed without merging**
